name    = "Isle of Ansur"
credits = "Toma400"
url     = "linktr.ee/toma400"
logo    = "ioa_logo.png"
version = "0.3b"

description  = '''
Core mod for Isle of Ansur game, contains all files required for the game to run properly
'''

[requirements] # needs to be at the end to not be buggy
# none