name    = "Isle of Ansur"
credits = "Toma400"
url     = "linktr.ee/toma400"

requirements = [
]
description  = '''
Core mod for Isle of Ansur game, contains all files required for the game to run properly
'''