lang__name                 = "English" #this value has to be your own language name, translated

menu__button_start         = "New Game"
menu__button_load          = "Load Game"
menu__button_arena         = "Arena"
menu__button_settings      = "Settings"
menu__button_packs         = "Packs"
menu__button_exit          = "Exit"
menu__update               = "Update is available!"
menu__pack_error           = "Error during loading packs"

menu__sett_general         = "General"
menu__sett_general_res     = "Screen Resolution"
menu__sett_general_lang    = "Language"
menu__sett_general_music   = "Music Volume"
menu__sett_tech            = "Technical"
menu__sett_tech_legacy     = "Legacy Unpacking"
menu__sett_tech_log_limit  = "Log Limit"
menu__sett_tech_log_rv     = "Remove Logs"
menu__sett_tech_listbox    = "List Mode"
menu__sett_tech_lb_amount  = "List Elements Amount"
menu__sett_tech_lb_size    = "List Elements Size"
menu__sett_tech_text_size  = "Text Size"
menu__sett_tech_ver_notif  = "Update Notification"
menu__sett_back            = "Back to menu"

ccrt__gen_gender   = "Gender"
ccrt__gen_race     = "Race"
ccrt__gen_class    = "Class"
ccrt__gen_name     = "Name"
ccrt__gen_religion = "Religion"
ccrt__gen_origin   = "Origin"
ccrt__gen_history  = "History"

ccrt__gen_category1        = "Gender"
ccrt__gen_category2        = "Race"
ccrt__gen_category3        = "Class"
ccrt__gen_category4        = "Name"
ccrt__gen_category5        = "Points Distribution"
ccrt__gen_category6        = "Religion"
ccrt__gen_category7        = "Character Origin"
ccrt__gen_category8        = "Gameplay Settings"
ccrt__gen_category9        = "Summary"

ccrt__gender               = "Choice of gender affects slightly dialogues and some minor gameplay features."
ccrt__history              = "Write your story"

ccrt__name_exists          = "This name is already used"
ccrt__sett_hardcore        = "Permadeath"
ccrt__sett_hardcore_descr  = "Will lock the game after death, not allowing you to load it."
ccrt__end_name             = "Name"
ccrt__end_race             = "Race"
ccrt__end_class            = "Class"
ccrt__end_religion         = "Religion"
ccrt__end_origin           = "Origin"
ccrt__end_save             = "Save"
ccrt__end_save_warn        = '''
Character won't be available in current version, as it doesn't feature gameplay. It will be possible to load the profile later.
'''

load__packs_used      = "Packs used"
load__load            = "Load saved game"
load__restore         = "Overwrite from cache"
load__remove          = "Remove saved game"

pack__type_stats      = "Statpack"
pack__type_themes     = "Themepack"
pack__type_worlds     = "Worldpack"
pack__name            = "Name"
pack__authors         = "Authors"
pack__version         = "Version"
pack__descr           = "Description"
pack__req             = "Dependencies"
# end

menu__load_choose          = "Choose your save"
menu__load_choose_hint     = "[use numbers or precise name]"
menu__load_save_deleted    = "Saved game successfully deleted!"
menu__load_save_unsaved    = "Save file wasn't saved before. Saving from in-game data."
menu__load_action1         = "[use any non-assigned button to go back to menu]" #will be removed
menu__load_action2         = "[use slash '/' before name to delete profile]" #will be removed
menu__settings_choose      = "Select setting to switch"
menu__settings_action      = "[use any non-numerical button to go back to menu]" #will be removed
menu__warn_core_missing    = "Core files are not loaded! Restricted menu options."

pack__general_info         = "PACKS LOADED"
pack__actions_opt1         = "Enter name of pack to open its settings"
pack__actions_opt2         = "Use -unzip- key to unzip mod files" #this should be deprecated eventually (or made greyed out button if autoimport is on)
pack__actions_opt3         = "Press -q- to leave to menu"
pack__lister_id            = "Pack ID"
pack__lister_type          = "Type"
pack__lister_credits       = "Credits"
pack__lister_disabled      = "Pack disabled"
pack__lister_action1       = "[link] Open the link"
pack__lister_action2       = "[switch] Change mod status (enabled/disabled)"
pack__lister_action3       = "[q] Return to pack list"
pack__error_not_exist      = "Pack with this name does not exist!"

game__init_charname        = "Type your character name"
game__init_charname_rv     = "Type -0- to cancel"
game__init_gender          = "Choose your gender"
game__init_race            = "Choose your race"
game__init_class           = "Choose your class"
game__init_class_excl      = "Class is exclusive for race you don't represent!" #will be removed, it is here just bc I'm dumb
game__init_attr            = "Choose attribute you want to enhance"
game__init_skill           = "Choose ability you want to enhance"

stat__gen_name             = "Name"
stat__gen_gender           = "Gender"
stat__gen_gender1          = "Male"
stat__gen_gender2          = "Female"
stat__gen_location         = "Location"

stat__hint_hp              = "Health Points"
stat__hint_mp              = "Magic Points"
stat__hint_sp              = "Energy"
stat__hint_xp              = "Experience"
stat__hint_weight          = "Weight"
stat__hint_xp_required     = "Experience for new level"
stat__hint_level           = "Level"
stat__hint_pwr_tech        = "Power Value: Technology"
stat__hint_pwr_magic       = "Power Value: Magic"
stat__hint_pwr_conn        = "Power Value: Connection"
stat__hint_pwr_void        = "Power Value: Void"
stat__hint_pwm_diamond     = "Power Modifier: Structural Penalty Negation"
stat__hint_pwm_moon        = "Power Modifier: Harmony Penalty Negation"
stat__hint_armour          = "Armour"

stat__perk_assassin_hit    = "Assassin Hit"
stat__perk_trader_sight    = "Trader Sight"
stat__perk_vehicle_driving = "Vehicle Driving"
stat__perk_toxin_immunity  = "Toxin Immunity"
stat__perk_animal_friend   = "Friends of Animals"
stat__perk_animal_trainer  = "Animal Training"
stat__perk_berserk         = "Berserk"
stat__perk_step_on_water   = "Walking on Water"
stat__perk_flying_monk     = "Flying Priest"
stat__perk_vampirism       = "Vampirism"
stat__perk_ritual_tongue   = "Ritual Tongues"
stat__perk_ancient_tongue  = "Ancient Architects' Tongue"

gen__enabled               = "Enabled"
gen__disabled              = "Disabled"
gen__proportional          = "Proportional"
gen__sized                 = "Sized"

pack__themes               = "Themepack"
pack__worlds               = "Worldpack"
pack__stats                = "Statpack"

system__text_load_fail     = "Text failed to load"