menu__button_start         = "[1] START THE GAME"
menu__button_load          = "[2] LOAD THE GAME"
menu__button_settings      = "[3] SETTINGS"
menu__button_packs         = "[4] PACKS"
menu__button_exit          = "[5] EXIT THE GAME"

menu__load_choose          = "Choose your save"
menu__load_choose_hint     = "[use numbers or precise name]"
menu__load_save_deleted    = "Saved game successfully deleted!"
menu__load_save_unsaved    = "Save file wasn't saved before. Saving from in-game data."
menu__load_action1         = "[use any non-assigned button to go back to menu]" #will be removed
menu__load_action2         = "[use slash '/' before name to delete profile]" #will be removed
menu__settings_choose      = "Select setting to switch"
menu__settings_action      = "[use any non-numerical button to go back to menu]" #will be removed
menu__warn_core_missing    = "Core files are not loaded! Restricted menu options."

pack__general_info         = "PACKS LOADED"
pack__actions_opt1         = "Enter name of pack to open its settings"
pack__actions_opt2         = "Use -unzip- key to unzip mod files" #this should be deprecated eventually (or made greyed out button if autoimport is on)
pack__actions_opt3         = "Press -q- to leave to menu"
pack__lister_id            = "Pack ID"
pack__lister_type          = "Type"
pack__lister_credits       = "Credits"
pack__lister_disabled      = "Pack disabled"
pack__lister_action1       = "[link] Open the link"
pack__lister_action2       = "[switch] Change mod status (enabled/disabled)"
pack__lister_action3       = "[q] Return to pack list"
pack__error_not_exist      = "Pack with this name does not exist!"

game__init_charname        = "Type your character name"
game__init_charname_rv     = "Type -0- to cancel"
game__init_gender1         = "Choose your gender"
game__init_gender2         = "[1] Male"
game__init_gender3         = "[2] Female"
game__init_gender4         = "[3] Non-binary"
game__init_race            = "Choose your race"
game__init_class           = "Choose your class"
game__init_class_excl      = "Class is exclusive for race you don't represent!" #will be removed, it is here just bc I'm dumb
game__init_attr            = "Choose attribute you want to enhance"
game__init_abil            = "Choose ability you want to enhance"

stat__atr_charisma         = "Charisma"
stat__atr_agility          = "Agility"
stat__atr_endurance        = "Endurance"
stat__atr_intelligence     = "Intelligence"
stat__atr_strength         = "Strength"
stat__sk_shortswords       = "Shortswords"
stat__sk_longswords        = "Longswords"
stat__sk_archery           = "Archery"
stat__sk_firearms          = "Firearms"
stat__sk_castspelling      = "Castspelling"
stat__sk_restoration       = "Restoration"
stat__sk_transformation    = "Transformation"
stat__sk_destruction       = "Destruction"
stat__sk_necromancy        = "Necromancy"
stat__sk_connection        = "Connection"
stat__sk_trade             = "Trade"
stat__sk_persuasion        = "Persuasion"
stat__sk_musicality        = "Musicality"
stat__sk_repair            = "Repair"
stat__sk_traps             = "Traps"
stat__sk_resources         = "Resource Processing"
stat__sk_tools             = "Tools"
stat__sk_smithery          = "Smithery"
stat__sk_herbalism         = "Herbalism"
stat__sk_alchemy           = "Alchemy"
stat__sk_lockpicking       = "Lockpicking"
stat__sk_sneaking          = "Sneaking"
stat__sk_trapspotting      = "Trapspotting"
stat__sk_pickpocketing     = "Pickpocketing"
stat__sk_healing           = "Healing"
stat__sk_cooking           = "Cooking"
stat__sk_survival          = "Survival"
stat__sk_toughness         = "Toughness"
stat__gen_name             = "Name"
stat__gen_gender           = "Gender"
stat__gen_location         = "Location"

stat__hint_hp              = "Health Points"
stat__hint_mp              = "Magic Points"
stat__hint_sp              = "Energy"
stat__hint_xp              = "Experience"
stat__hint_weight          = "Weight"
stat__hint_xp_required     = "Experience for new level"
stat__hint_level           = "Level"
stat__hint_pwr_tech        = "Power Value: Technology"
stat__hint_pwr_magic       = "Power Value: Magic"
stat__hint_pwr_conn        = "Power Value: Connection"
stat__hint_pwr_void        = "Power Value: Void"
stat__hint_pwm_diamond     = "Power Modifier: Structural Penalty Negation"
stat__hint_pwm_moon        = "Power Modifier: Harmony Penalty Negation"
stat__hint_armour          = "Armour"

stat__perk_assassin_hit    = "Assassin Hit"
stat__perk_trader_sight    = "Trader Sight"
stat__perk_vehicle_driving = "Vehicle Driving"
stat__perk_toxin_immunity  = "Toxin Immunity"
stat__perk_animal_friend   = "Animal Friend"
stat__perk_animal_trainer  = "Animal Trainer"

system__text_load_fail     = "Text failed to load"