menu__button_start    = "[1] START THE GAME"
menu__button_load     = "[2] LOAD THE GAME"
menu__button_settings = "[3] SETTINGS"
menu__button_packs    = "[4] PACKS"
menu__button_exit     = "[5] EXIT THE GAME"