# GENERAL
# VERSIONING SHOULD MATCH THE EXACT STATUS OF THE VERSION.
name    = "The Isle of Ansur"
status  = "pre alpha"
version = "3"

# RELEASE
# RELEASE VERSIONING. SHOULD MATCH LATEST PUBLISHED VERSION, NOT DEVELOPED ONE.
release_status  = "pre alpha"
release_version = "2"

# CYCLE
cname = "Between Shadows and Light"
cycle = "0"

# TECHNICAL
save_system = "1.0"
vanilla_modules = [
    "ansur"
]