# GENERAL
# VERSIONING SHOULD MATCH THE EXACT STATUS OF THE VERSION.
name    = "The Isle of Ansur"
status  = "pre alpha"
version = "7"

# RELEASE
# RELEASE VERSIONING. SHOULD MATCH LATEST PUBLISHED VERSION, NOT DEVELOPED ONE.
release_status  = "pre alpha"
release_version = "6"

# CYCLE
cycle_name   = "Between Shadows and Light"
cycle_number = "0"

# TECHNICAL
vanilla_modules = [
    "ansur"
]
languages = [
    "english"#,
    #"polish"
]