# GENERAL
# VERSIONING SHOULD MATCH THE EXACT STATUS OF THE VERSION.
name    = "The Isle of Ansur"
status  = "pre alpha"
version = "4"

# RELEASE
# RELEASE VERSIONING. SHOULD MATCH LATEST PUBLISHED VERSION, NOT DEVELOPED ONE.
release_status  = "pre alpha"
release_version = "3b"

# CYCLE
cycle_name   = "Between Shadows and Light"
cycle_number = "0"

# TECHNICAL
save_system = "1.0"
vanilla_modules = [
    "ansur"
]
languages = [
    "english",
    "polish"
]