races__baedoorian = "Human, Born in Baedoor"
races__kaerian    = "Human, Born in Kaer"
races__ormath     = "Ormath"

classes__undefined     = "Undefined"
classes__fighter       = "Fighter"
classes__ormath_shaman = "Ormath Shaman"

gender__male       = "Man"
gender__female     = "Woman"
gender__non_binary = "Non-binary"

stat__atr_charisma     = "Charisma"
stat__atr_agility      = "Agility"
stat__atr_endurance    = "Endurance"
stat__atr_intelligence = "Intelligence"
stat__atr_strength     = "Strength"

stat__sk_shortswords         = "Shortswords"
stat__sk_longswords          = "Longswords"
stat__sk_archery             = "Archery"
stat__sk_firearms            = "Firearms"
stat__sk_persuasion          = "Persuasion"
stat__sk_trade               = "Trade"
stat__sk_destruction_magic   = "Destruction Magic"
stat__sk_toughness           = "Toughness"
stat__sk_healing             = "Healing"
stat__sk_survival            = "Survival"
stat__sk_tools               = "Tools"
stat__sk_repair              = "Repair"
stat__sk_resource_processing = "Resource Processing"
stat__sk_herbalism           = "Herbalism"
stat__sk_cooking             = "Cooking"
stat__sk_connection_bond     = "Connection Bond"

religion__theism  = "Theism (Non-specific)"
religion__atheism = "Atheism"

origin__wanderer = "Wanderer"

#================================================================================================================================
# DESCRIPTIONS
#================================================================================================================================
races__baedoorian_descr = '''
Human race is known to be flexible and very adaptive to its environment. One of common qualities of humans is their mobility and openness to chances, making them overall great merchants and spokeperson, classic fighters, as well as technicians and mages.
What this race gains from being very fluid however, it loses on mastery. Human beings are rarely beyond bit-above-average in many aspects.
Despite those shortcomings, their assimilation skills let them be very expansive kind, filling most of places in Baedoor universe.

Inhabitants of Baedoor are descendants of jitadians, and as such they are great sailors, invested in technology and trade, with love to some sophisticated political play and artistry.
Unlike their grandfathers however, Baedoor culture was forged by fiery aristocrats and as such, it tends to get more hermetic, yet the passion built by many aristocratic homes drives the culture towards new discoveries and conquests.
Currently, Baedoor civilisation is considered as one of the most technologically advanced in whole universe.
'''
races__kaerian_descr = '''
Human race is known to be flexible and very adaptive to its environment. One of common qualities of humans is their mobility and openness to chances, making them overall great merchants and spokeperson, classic fighters, as well as technicians and mages.
What this race gains from being very fluid however, it loses on mastery. Human beings are rarely beyond bit-above-average in many aspects.
Despite those shortcomings, their assimilation skills let them be very expansive kind, filling most of places in Baedoor universe.

Kaer humans are known to be inhabitants of Kaer, dark lands on the south of Baedoor. It is bundled name that counts both Serj and those with serj blood who lived in mixed marriages with Baedoor occupants or other races living in Kaer.
Serj built their unique civilisation in forests alongside kehts, keeping mostly north part of the island. Their history is tainted with many wars, mostly with kehts, which really depleted their military strength.
Despite that, serj humans were very talented in processing mined goods and craft of wooden and clay furniture, as well as savage in fight, even with very poor equipment.
Nowadays, serj population is much smaller than it used to be, but free of Empire's chains, they slowly come back to their old power, trying to restitute their historical cities near eastern mountain range.
'''
races__ormath_descr = '''
Ormath race is quite odd race of short, grayskinned beings living in tribes on Arennan desert. They are heavily structured in their hierarchical societies built around Elders and most importantly, Shaman being the guide of whole tribe.
They also perform many daily activities in groups, either of families and friends, or whole tribe. This community focus is one of recurring qualities of ormath race.
Aside of that, ormaths are used to harsh environment, which resulted in them getting strong immunity system and survival abilities.

Faith makes huge part of ormath's life, however unlike structured religions, this race connects to the wind being natural occurence on Arennan desert. Shamans are sometimes called as "those who knows tongue of winds".
Ormaths believe wind is a driving force of all spirits, guiding souls of those who passed away, and bringing new beings to life.
There are many spirits in ormaths demonology, which also explains why shamans are considered as protective mediators, often calming down those spirits that try to bring chaos to the tribe, sometimes even by literal fight with the element.
'''
classes__undefined_descr = '''
Those picking <b>undefined</b> class do not have focus on any specific skill, but they learn experience quicker.

 Charisma +1
'''
classes__fighter_descr = '''
<b>Fighters</b> are great dealing with melee fight and all kinds of swords.

 Shortswords +1
 Longswords +1
 Toughness +1
 Firearms -1
 Archery -1
'''
classes__ormath_shaman_descr = '''
<b>Ormath shaman</b> is special class that let you control environment by shamanic spirit.

 Connection +2
 Herbalism +1
 Healing +1
 Firearms -2
'''
stat__atr_charisma_descr = '''

'''
stat__atr_agility_descr = '''

'''
stat__atr_endurance_descr = '''

'''
stat__atr_intelligence_descr = '''

'''
stat__atr_strength_descr = '''

'''
stat__sk_shortswords_descr = '''

'''
stat__sk_longswords_descr = '''

'''
stat__sk_archery_descr = '''

'''
stat__sk_firearms_descr = '''

'''
stat__sk_persuasion_descr = '''

'''
stat__sk_trade_descr = '''

'''
stat__sk_destruction_magic_descr = '''

'''
stat__sk_toughness_descr = '''

'''
stat__sk_healing_descr = '''

'''
stat__sk_survival_descr = '''

'''
stat__sk_tools_descr = '''

'''
stat__sk_repair_descr = '''

'''
stat__sk_resource_processing_descr = '''

'''
stat__sk_herbalism_descr = '''

'''
stat__sk_cooking_descr = '''

'''
stat__sk_connection_bond_descr = '''

'''

religion__theism_descr = '''
You believe in some kind of external forces, be it God or some spirits, but you don't necessarily know or want to investigate. Or you just find this topic overall too vague to find the truth.

This choice brings no advantages, disadvantages nor obligations. Pick it if you want to declare being a theist without any side-effects of concrete faith.
'''
religion__atheism_descr = '''
You don't believe in anything supernatural, despite Baedoor having magical phenomenons, you find them proven by science and not worth depicting as anything beyond clever tricks.

This choice brings no advantages, disadvantages nor obligations.
'''

origin__wanderer_descr = '''
You find yourself travelling to the West Baedoor on ship. You don't know what to do with your life, but decided to try your luck with simply escaping your current daily routines and search for some work in the most cosmopolitan city in current era.
'''