races__baedoorian  = "Człowiek, Urodzony w Baedoor"
races__kaerian     = "Człowiek, Urodzony w Kaer"
races__jitadian    = "Człowiek, Urodzony w Jitado"
races__mesinpean   = "Człowiek, Urodzony w Mes Inpei"
races__mrran       = "Człowiek, Urodzony w Eimr"
races__lunanians   = "Człowiek, Urodzony na Kontynencie Księżyca"
races__nordwinians = "Człowiek, Urodzony na Wyspach Północych"
races__ormath      = "Ormath"
races__ghlodd      = "Głodd"
races__lunatri     = "Lunatri"
races__voitri      = "Voitri"
races__saphtri     = "Saphtri"
races__pahtri      = "Pahtri"

classes__undefined     = "Niezdefiniowany"
classes__swordsman     = "Szermierz"
classes__gunslinger    = "Rewolwerowiec"
classes__sharpshooter  = "Stzelec wyborowy"
classes__archer        = "Łucznik"
classes__illusionist   = "Iluzjonista"
classes__priest        = "Kapłan"
classes__rogue         = "Łotr"
classes__assassin      = "Asasyn"
classes__bard          = "Bard"
classes__merchant      = "Kupiec"
classes__blacksmith    = "Kowal"
classes__outlander     = "Przybysz"
classes__headhunter    = "Łowca Głów"
classes__ormath_shaman = "Ormacki Szaman"

gender__male       = "Mężczyzna"
gender__female     = "Kobieta"
gender__non_binary = "Osoba niebinarna"

stat__atr_charisma         = "Charyzma"
stat__atr_agility          = "Zręczność"
stat__atr_endurance        = "Wytrzymałość"
stat__atr_intelligence     = "Inteligencja"
stat__atr_strength         = "Siła"

stat__sk_handfight                   = "Walka wręcz"
stat__sk_shortswords                 = "Krótkie miecze"
stat__sk_longswords                  = "Długie miecze"
stat__sk_axes                        = "Topory"
stat__sk_blunts                      = "Obuchy"
stat__sk_polearms                    = "Broń drzewcowa"
stat__sk_aim                         = "Celność"
stat__sk_throwing                    = "Broń rzucana"
stat__sk_archery                     = "Łuki"
stat__sk_crossbows                   = "Kusze"
stat__sk_light_firearms              = "Lekka broń palna"
stat__sk_heavy_firearms              = "Ciężka broń palna"
stat__sk_light_armour                = "Lekki pancerz"
stat__sk_medium_armour               = "Średni pancerz"
stat__sk_heavy_armour                = "Ciężki pancerz"
stat__sk_blocking                    = "Blokowanie"
stat__sk_spellcasting                = "Rzucanie zaklęć"
stat__sk_common_magic                = "Magia pospolita"
stat__sk_path_magic                  = "Magia drogi"
stat__sk_common_magic_void           = "Pustka"
stat__sk_common_magic_fire           = "Ogień"
stat__sk_common_magic_electricity    = "Elektryczność"
stat__sk_common_magic_soul           = "Dusza"
stat__sk_common_magic_wind           = "Wiatr"
stat__sk_common_magic_ice            = "Lód"
stat__sk_common_magic_water          = "Woda"
stat__sk_common_magic_earth          = "Ziemia"
stat__sk_common_magic_destruction    = "Destrukcja"
stat__sk_common_magic_absorption     = "Absorpcja"
stat__sk_common_magic_illusion       = "Iluzja"
stat__sk_common_magic_transformation = "Transformacja"
stat__sk_common_magic_evocation      = "Ewokacja"
stat__sk_common_magic_restoration    = "Odnowienie"
stat__sk_path_magic_dream            = "Droga Snu"
stat__sk_path_magic_death            = "Droga Śmierci"
stat__sk_path_magic_erd              = "Droga Erdyjska"
stat__sk_path_magic_lunatri          = "Droga Wyższych Tri"
stat__sk_path_magic_ormath           = "Droga Ormacka"
stat__sk_path_magic_terten           = "Droga Terteńska"
stat__sk_path_magic_keht             = "Droga Kehtyjska"
stat__sk_scrolls_writing             = "Pisanie zwojów"
stat__sk_mores_casting               = "Zaklinanie morów"
stat__sk_unsealing                   = "Odpięczetowanie"
stat__sk_trade                       = "Handel"
stat__sk_persuasion                  = "Perswazja"
stat__sk_lockpicking                 = "Otwieranie zamków"
stat__sk_sneaking                    = "Skradanie się"
stat__sk_pickpocketing               = "Kieszonkostwo"
stat__sk_traps_designing             = "Tworzenie pułapek"
stat__sk_traps_spotting              = "Wykrywanie pułapek"
stat__sk_hunting                     = "Polowanie"
stat__sk_fishing                     = "Łowienie"
stat__sk_sewing                      = "Krawiectwo"
stat__sk_carpentry                   = "Stolarstwo"
stat__sk_pottery                     = "Garncarstwo"
stat__sk_stonemasonry                = "Kamieniarstwo"
stat__sk_ore_processing              = "Przetwarzanie rud"
stat__sk_smithing                    = "Kowalstwo"
stat__sk_herbalism                   = "Zielarstwo"
stat__sk_alchemy                     = "Alchemia"
stat__sk_cooking                     = "Gotowanie"
stat__sk_wound_treatment             = "Opatrywanie ran"
stat__sk_horse_riding                = "Jazda na koniu"
stat__sk_boat_driving                = "Prowadzenie łodzi"
stat__sk_animal_taming               = "Oswajanie zwierząt"
stat__sk_musicality                  = "Muzykalność"
stat__sk_athletics                   = "Atletyka"
stat__sk_toughness                   = "Twardość"
stat__sk_survival                    = "Przetrwanie"

religion__theism  = "Teizm (Niereligijny)"
religion__atheism = "Ateizm"

origin__wanderer = "Podróżnik"