races__baedoorian  = "Człowiek, Urodzony w Baedoor"
races__kaerian     = "Człowiek, Urodzony w Kaer"
races__jitadian    = "Człowiek, Urodzony w Jitado"
races__mesinpean   = "Człowiek, Urodzony w Mes Inpei"
races__mrran       = "Człowiek, Urodzony w Eimr"
races__nordwinians = "Człowiek, Urodzony na Wyspach Północych"
races__ormath      = "Ormath"
races__ghlodd      = "Głodd"
races__lunatri     = "Lunatri"
races__voitri      = "Voitri"
races__saphtri     = "Saphtri"
races__pahtri      = "Pahtri"

classes__undefined     = "Niezdefiniowany"
classes__swordsman     = "Szermierz"
classes__gunslinger    = "Rewolwerowiec"
classes__sharpshooter  = "Stzelec wyborowy"
classes__archer        = "Łucznik"
classes__illusionist   = "Iluzjonista"
classes__priest        = "Kapłan"
classes__rogue         = "Łotr"
classes__assassin      = "Asasyn"
classes__bard          = "Bard"
classes__merchant      = "Kupiec"
classes__blacksmith    = "Kowal"
classes__outlander     = "Przybysz"
classes__headhunter    = "Łowca Głów"
classes__ormath_shaman = "Ormacki Szaman"

gender__male       = "Mężczyzna"
gender__female     = "Kobieta"
gender__non_binary = "Osoba niebinarna"

stat__atr_charisma         = "Charyzma"
stat__atr_agility          = "Zręczność"
stat__atr_endurance        = "Wytrzymałość"
stat__atr_intelligence     = "Inteligencja"
stat__atr_perception       = "Percepcja"
stat__atr_strength         = "Siła"

stat__sk_handfight                   = "Walka wręcz"
stat__sk_shortswords                 = "Krótkie miecze"
stat__sk_longswords                  = "Długie miecze"
stat__sk_axes                        = "Topory"
stat__sk_blunts                      = "Obuchy"
stat__sk_polearms                    = "Broń drzewcowa"
stat__sk_aim                         = "Celność"
stat__sk_throwing                    = "Broń rzucana"
stat__sk_archery                     = "Łuki"
stat__sk_crossbows                   = "Kusze"
stat__sk_light_firearms              = "Lekka broń palna"
stat__sk_heavy_firearms              = "Ciężka broń palna"
stat__sk_light_armour                = "Lekki pancerz"
stat__sk_medium_armour               = "Średni pancerz"
stat__sk_heavy_armour                = "Ciężki pancerz"
stat__sk_blocking                    = "Blokowanie"
stat__sk_spellcasting                = "Rzucanie zaklęć"
stat__sk_common_magic                = "Magia pospolita"
stat__sk_path_magic                  = "Magia drogi"
stat__sk_common_magic_void           = "Pustka"
stat__sk_common_magic_fire           = "Ogień"
stat__sk_common_magic_electricity    = "Elektryczność"
stat__sk_common_magic_soul           = "Dusza"
stat__sk_common_magic_wind           = "Wiatr"
stat__sk_common_magic_ice            = "Lód"
stat__sk_common_magic_water          = "Woda"
stat__sk_common_magic_earth          = "Ziemia"
stat__sk_common_magic_destruction    = "Destrukcja"
stat__sk_common_magic_absorption     = "Absorpcja"
stat__sk_common_magic_illusion       = "Iluzja"
stat__sk_common_magic_transformation = "Transformacja"
stat__sk_common_magic_evocation      = "Ewokacja"
stat__sk_common_magic_restoration    = "Odnowienie"
stat__sk_path_magic_dream            = "Droga Snu"
stat__sk_path_magic_death            = "Droga Śmierci"
stat__sk_path_magic_erd              = "Droga Erdyjska"
stat__sk_path_magic_lunatri          = "Droga Wyższych Tri"
stat__sk_path_magic_ormath           = "Droga Ormacka"
stat__sk_path_magic_terten           = "Droga Terteńska"
stat__sk_path_magic_keht             = "Droga Kehtyjska"
stat__sk_scrolls_writing             = "Pisanie zwojów"
stat__sk_mores_casting               = "Zaklinanie morów"
stat__sk_unsealing                   = "Odpięczetowanie"
stat__sk_trade                       = "Handel"
stat__sk_persuasion                  = "Perswazja"
stat__sk_lockpicking                 = "Otwieranie zamków"
stat__sk_sneaking                    = "Skradanie się"
stat__sk_pickpocketing               = "Kieszonkostwo"
stat__sk_traps_designing             = "Tworzenie pułapek"
stat__sk_traps_spotting              = "Wykrywanie pułapek"
stat__sk_hunting                     = "Polowanie"
stat__sk_fishing                     = "Łowienie"
stat__sk_sewing                      = "Krawiectwo"
stat__sk_carpentry                   = "Stolarstwo"
stat__sk_pottery                     = "Garncarstwo"
stat__sk_stonemasonry                = "Kamieniarstwo"
stat__sk_ore_processing              = "Przetwarzanie rud"
stat__sk_smithing                    = "Kowalstwo"
stat__sk_herbalism                   = "Zielarstwo"
stat__sk_alchemy                     = "Alchemia"
stat__sk_cooking                     = "Gotowanie"
stat__sk_wound_treatment             = "Opatrywanie ran"
stat__sk_horse_riding                = "Jazda na koniu"
stat__sk_boat_driving                = "Prowadzenie łodzi"
stat__sk_animal_taming               = "Oswajanie zwierząt"
stat__sk_musicality                  = "Muzykalność"
stat__sk_athletics                   = "Atletyka"
stat__sk_toughness                   = "Twardość"
stat__sk_survival                    = "Przetrwanie"

religion__theism  = "Teizm (Niereligijny)"
religion__atheism = "Ateizm"

origin__wanderer = "Podróżnik"

#================================================================================================================================
# OPISY
#================================================================================================================================
# RASY
#-----------------------
races__baedoorian_descr = '''
Ludzka rasa jest znana ze swojej elastyczności i adaptacji do środowiska. Jedną z częstych cech ludzi jest ich mobilność i otwartość na możliwości, czyniąc z nich świetnych kupców i mówców, wojowników, jak i techników czy magów.
Co jednak rasa ta zyskuje z przystosowania, to traci ona na mistrzostwie. Ludzie rzadko osiągają wyniki powyżej średniej w wielu aspektach.
Mimo tych mankamentów, ich zdolności asymilacji pozwalają być im bardzo ekspansywną grupą, zaludniającą większość miejsc uniwersum Baedoor.

Mieszkańcy Baedoor są potomkami jitadczyków, dziedzicząc od nich zamiłowanie do żeglarstwa, talent do technologii i handlu, jak i miłość do złożonych gier politycznych i sztuki.
Odmiennie jednak od ich przodków, kultura baedoorska była ukształtowana przez zapalczywych arystokratów. Przez to też ma ona tendencję być bardziej hermetyczna, jednakże pasja wielu arystokratycznych domów ciągnie kulturę baedoorską ku kolejnym odkryciom i podbojom.
Obecnie cywilizacja baedoorska jest uważana za jedną z najbardziej zaawansowanych technologicznie w uniwersum. Jest jednak politycznie osłabiona przez podział Imperium, który dokonał się pod koniec Starej Ery.
'''
races__kaerian_descr = '''
Ludzka rasa jest znana ze swojej elastyczności i adaptacji do środowiska. Jedną z częstych cech ludzi jest ich mobilność i otwartość na możliwości, czyniąc z nich świetnych kupców i mówców, wojowników, jak i techników czy magów.
Co jednak rasa ta zyskuje z przystosowania, to traci ona na mistrzostwie. Ludzie rzadko osiągają wyniki powyżej średniej w wielu aspektach.
Mimo tych mankamentów, ich zdolności asymilacji pozwalają być im bardzo ekspansywną grupą, zaludniającą większość miejsc uniwersum Baedoor.

Kaeryjczycy są mieszkańcami Kaeru, ciemnych lądów na południe od Baedoor. Wliczają się w nich Serjanie, jak i również ci z seryjską krwią, z mieszanych małżeństw różnego rodzaju.
Serjanie zbudowali swoją cywilizację w lasach, sąsiadując z kehtami, zaludniając głównie północną część wyspy. Ich historia jest przepełniona wieloma wojnami, głównie z cywilizacją kehtów, które to znacząco osłabiły ich militarną siłę.
Od samych początków, serjanie byli bardzo utalentowani w przetwarzaniu wydobytych dóbr, jak i rzemieślnictwie drewna i gliny. Ich styl walki przepełniony był pasją, przez co nie było dla nich przeszkodą nawet słabe uzbrojenie.
W obecnych czasach, populacja serjan jest dużo mniejsza, jednak wolni od wpływów Imperium, wracają powoli ku swojej przeszłej chwale, próbując odbudować swoje historyczne miasta obok łańcucha górskiego na wschodzie Kaeru.
'''
races__jitadian_descr = '''
Ludzka rasa jest znana ze swojej elastyczności i adaptacji do środowiska. Jedną z częstych cech ludzi jest ich mobilność i otwartość na możliwości, czyniąc z nich świetnych kupców i mówców, wojowników, jak i techników czy magów.
Co jednak rasa ta zyskuje z przystosowania, to traci ona na mistrzostwie. Ludzie rzadko osiągają wyniki powyżej średniej w wielu aspektach.
Mimo tych mankamentów, ich zdolności asymilacji pozwalają być im bardzo ekspansywną grupą, zaludniającą większość miejsc uniwersum Baedoor.

Jitadczycy są doświadczonymi żeglarzami i inżynierami, przodując w odkryciach technologicznych w najstarszych czasach. Ich broń palna stanowiła znak najwyższej jakości, stanowiąc klasyczne wyposażenie rozlicznych armii.
Jest powszechnie uznawane, iż jitadczycy byli pierwszymi, którzy używali prochu w swojej technologii, budując przemysł rusznikarski obok głoddyjskiego, zbudowanego jednak na odmiennych odkryciach.
Choć znaczenie międzynarodowe Jitado osłabło w trakcie Starej Ery, jest ono wciąż uznawane za jedno z najbardziej wpływowych po dziś dzień, szczególnie przez ich rozciągnięte szeroko szlaki handlowe.
Jitadczycy zwykli dbać o ekonomię swego państwa, co uczyniło ich państwo jednym z najbardziej prosperujących miejsc od początku wieków, odpornym na wiele kryzysów.
'''
races__mesinpean_descr = '''
Ludzka rasa jest znana ze swojej elastyczności i adaptacji do środowiska. Jedną z częstych cech ludzi jest ich mobilność i otwartość na możliwości, czyniąc z nich świetnych kupców i mówców, wojowników, jak i techników czy magów.
Co jednak rasa ta zyskuje z przystosowania, to traci ona na mistrzostwie. Ludzie rzadko osiągają wyniki powyżej średniej w wielu aspektach.
Mimo tych mankamentów, ich zdolności asymilacji pozwalają być im bardzo ekspansywną grupą, zaludniającą większość miejsc uniwersum Baedoor.

Mesinpejczycy są najstarszą ludzką kulturą kontynentu, zaludniając jedną z najbardziej zróżnicowanych krain jaką jest wyspa Mes Inpei.
W czasach przederowych imperiów dochodzących do władzy, Mes Inpea była uznawana za jedną z dwóch najpotężniejszych cywilizacji, zaraz po Imperium Głoddyjskim. Wraz z Jitado, stanowiły one dowód potęgi i siły Starożytnego Kontynentu.
Podczas gdy mesinpejczycy nie posiadają żadnych wyróżniających cech militarnych czy magicznych, są oni dobrymi rzemieślnikami, wyprzedzając pozostałe cywilizacje w różnorodności i jakości wytwarzanych dóbr.
Kultura mesinpejska była bardzo wpływową na późniejsze cywilizacje ludzkie, zaznaczając znaczenie tego kraju w trakcie jego świetności.
'''
races__mrran_descr = '''
Ludzka rasa jest znana ze swojej elastyczności i adaptacji do środowiska. Jedną z częstych cech ludzi jest ich mobilność i otwartość na możliwości, czyniąc z nich świetnych kupców i mówców, wojowników, jak i techników czy magów.
Co jednak rasa ta zyskuje z przystosowania, to traci ona na mistrzostwie. Ludzie rzadko osiągają wyniki powyżej średniej w wielu aspektach.
Mimo tych mankamentów, ich zdolności asymilacji pozwalają być im bardzo ekspansywną grupą, zaludniającą większość miejsc uniwersum Baedoor.

Eimr może być uznany za krainę z najbardziej napiętą historią w całym uniwersum, targaną przez nieustanne konflikty.
Poza tymi o zewnętrznym charakterze, jak wielokrotna okupacja obcych mocarstw, wiele napięć i wojn wśród mrrańczyków ma naturę wewnętrzną, jako wynik wielu cywilizacji żyjących obok siebie.
Relatywna jałowość ziemi również utrudnia rozwój kraju, powodując iż wielu ucieka się w kradzież i rozbój jako metodę przetrwania. Eimr jest podzielone na wiele terytorii o samozwańczym statusie, które pozostają ważnym podziałem nawet w obecnym czasie, gdy kraj jest formalnie zjednoczony.
Historia mrrańczyków jednak czyni ich bardzo uniwersalną cywilizacją, zdolną do szybszego uczenia się, gdyż jest to ich naturalny instynkt.
'''
races__nordwinians_descr = '''
Ludzka rasa jest znana ze swojej elastyczności i adaptacji do środowiska. Jedną z częstych cech ludzi jest ich mobilność i otwartość na możliwości, czyniąc z nich świetnych kupców i mówców, wojowników, jak i techników czy magów.
Co jednak rasa ta zyskuje z przystosowania, to traci ona na mistrzostwie. Ludzie rzadko osiągają wyniki powyżej średniej w wielu aspektach.
Mimo tych mankamentów, ich zdolności asymilacji pozwalają być im bardzo ekspansywną grupą, zaludniającą większość miejsc uniwersum Baedoor.

Nordwińczycy są mieszkańcami wysp północnych, dwóch obecnych na kontynencie baedoorskim, i pozostałych na oddzielnym archipelagu dalej na północ.
Nordwińska kultura niesie ze sobą widoczne wpływy przodków, którzy to skolonizowali wyspę Baedoor przed pojawieniem się jitadczyków, jak i również północną część Kontynentu Księżycowego. Zależnie od miejsca, ich symbolika i architektura ulegała zmianie, dostosowując się do wpływów lokalnych społeczności.
Wbrew powszechnym w kulturze nordwińczyków symbolu topora, równie popularne były długie miecze i kolczugi, szczególnie dla ludów nordwińskich, które osiadły w cieplejszych rejonach.
Rodzinne wyspy nordwińczyków obfitowały w lasy, umożliwiając im sporą ekspertyzę w obróbce drewna, zarówno na meble jak i inne formy sztuki.
Lud nordwiński jest przywiązany do tradycji. Kultywuje społeczne ceremoniały, świętując je częstymi ucztami, traktowane jako lokalne wydarzenie.
'''
#-----------------------
# UMIEJĘTNOŚCI
#-----------------------
stat__sk_smithing_descr = '''
Najbardziej rozchwytywana forma rzemiosła, pozwalająca na przetwarzanie metali w różne narzędzia.
Podczas gdy zwykle kojarzone z bronią i pancerzami, kowalstwo pozwala wykuwać wszelkie formy, wliczając w to nawet przedmioty codziennego użytku.
'''
stat__sk_herbalism_descr = '''
Zielarstwo pozwala poprawnie rozpoznawać zioła i rośliny, jak i również rozumieć ich zastosowanie.
W połączeniu z alchemią, umiejętność ta zyskuje tym bardziej, iż zioła stanowią istotny składnik mikstur.
'''
stat__sk_alchemy_descr = '''
Sztuka tworzenia mikstur i płynów, jak i również trucizn i innych cieczy, które wpływają na użytkownika lub otoczenie.
Rośliny są częstym składnikiem receptur alchemicznych, co czyni zielarstwo świetnym uzupełnieniem dla alchemii.
'''
stat__sk_cooking_descr = '''
Pozwala ci przygotować lepsze posiłki, jak i również używać bardziej zaawansowanych przepisów do tworzenia zdrowego, pożywnego jedzenia.
'''
stat__sk_wound_treatment_descr = '''
Jak obyty jesteś w opatrywaniu ran i medycynie jako takiej. Pozwala ci się sprawniej leczyć.
'''
stat__sk_horse_riding_descr = '''
Twoje doświadczenie w jeździe konno, wpływające na prędkość podróży na ich grzbiecie, jak i skuteczność walki na koniu.
'''
stat__sk_boat_driving_descr = '''
Twoje doświadczenie w używaniu łodzi, wpływające na efektywność w ich użyciu - zarówno osiągania większych prędkości, jak i skuteczności w walce z nich.
'''
stat__sk_animal_taming_descr = '''
Jak łatwo przychodzi ci kontakt ze zwierzętami i ich oswajanie. Zależnie od charakteru zwierzęcia, odmienny poziom tej umiejętności będzie potrzebny.
'''
stat__sk_musicality_descr = '''
Jak dobrym muzykiem jesteś. Pozwala na granie bardziej złożonych kompozycji muzycznych, jak i użycie większej ilości instrumentów.
'''
stat__sk_athletics_descr = '''
Jak szybko się poruszasz, zarówno w normalnych warunkach, jak i podczas biegu czy pływania.
'''
stat__sk_toughness_descr = '''
Twoja odporność na fizyczne obrażenia. Wpływa na to, jak wiele obrażeń bez pancerza jesteś w stanie przyjąć.
'''
stat__sk_survival_descr = '''
Zdolności radzenia sobie w trudnych warunkach czy środowisku, wliczając w to przystosowanie organizmu. Pomaga w wielu sytuacjach podczas podróży przez nieprzyjazne tereny, jednak wpływ ten jest niemal zawsze jedynie pośredni.
'''
#-----------------------
# RELIGIE
#-----------------------
religion__theism_descr = '''
Wierzysz w zewnętrzne siły, Boga, bogów, czy też duchy lub energię, która otacza fizyczny świat. Niekoniecznie jesteś pewien, co dokładnie masz przez to na myśli, ale wiesz, że to istnieje.

Ten wybór nie przynosi żadnych korzyści, strat ani zobowiązań. Wybierz jeśli chcesz się zadeklarować jako teista bez żadnych skutków ubocznych konkretnej wiary.
'''
religion__atheism_descr = '''
Nie wierzysz w cokolwiek nadprzyrodzonego, mimo iż Baedoor pełne jest magicznych fenomenów - dla Ciebie są one udowodnione przez naukę i niewarte uznania za cokolwiek więcej niż sprytna szarlataneria.

Ten wybór nie przynosi żadnych korzyści, strat ani zobowiązań.
'''
#-----------------------
# POCHODZENIE
#-----------------------
origin__wanderer_descr = '''
Spacerujesz po pokładzie "Veno Edran", galeonu płynącego do Zachodniego Baedoor. Twoje życie było zbyt nijakie, więc zdecydowałeś się spróbować szczęścia - płącąc za podróż, uciekłeś z miejsca, którego miałeś dość.
Czułeś coś w swoim sercu, odrobinę lęku, ale również nadziei, więc uśmiechnąłeś się, wyobrażając sobie mgliste doki portu Nowego Baedoor.
Nowe Baedoor, najbardziej kosmopolitańskiego miasta tej ery, w której marzenia stają się rzeczywistością.
'''