[backgrounds]
menu = "menu_background.jpg"

[colours]


[fonts.general]
font_size = 0 # placeholder value
# size that will be adjusted, so you can use also v. big and v. weird fonts and still make it work with current resolution/graphical system of IoA

[fonts.menu]
_         = "ferrum.otf"
polish    = "ferrum.otf"    # broken
hungarian = "verve_hun.otf"