[backgrounds]
icon        = "ioa_logo.png"
logo        = "ioa_logo.png"
menu        = "menu_background.jpg"
location    = "game_background.jpg"
frame_up    = "frame_up.png"
frame_down  = "frame_down.png"
frame_left  = "frame_left.png"
frame_right = "frame_right.png"
frame_cr_lu = "frame_left_up.png"
frame_cr_ld = "frame_left_down.png"
frame_cr_ru = "frame_right_up.png"
frame_cr_rd = "frame_right_down.png"
clock       = "clock.png"
tooltip     = "tooltip_bg.png"

[fonts.colours]
disabled   = "#43403E"
enabled    = "#4E3510"
hovered    = "#7C613B"
background = "#4F3920" # currently unused
selected   = "#354A07"
choice     = "#1A5856"
warning    = "#660000"
other      = "#B0CA60"

[fonts.general]
font_size = 1.0   # fallback value (if not specificed precisely later)

[fonts.menu]
_         = ["ferrum_extended.otf", "1.0"]
polish    = ["ferrum_extended.otf", "1.0"]

[fonts.tooltip]
_         = ["ferrum_extended.otf", "1.0"]
polish    = ["ferrum_extended.otf", "1.0"]

[tooltip.colours]
background = "#7f6f55" # lack of this value will make tooltip transparent
text       = "#4E3510"

[tooltip.general]
padding_side = 2
padding_tops = 2