[backgrounds]
menu = "menu_background.jpg"

[colours]


[fonts.general]
font_size = 1.0

[fonts.menu]
_         = ["ferrum.otf",    "1.0"]
polish    = ["ferrum.otf",    "1.0"]    # broken
hungarian = ["verve_hun.otf", "1.0"]