loc__sea__veno_edran_deck_0       = "Veno Edran, Main Deck"

# DESCRIPTIONS
loc__sea__veno_edran_deck_0_descr = '''
It was a windy day. You saw beautiful sea before you, just as breeze flow through your hair.
'''