"login__listbox"   = "Projects"
"login__open"      = "Open the project"
"login__add"       = "Add new project"
"login__remove"    = "Remove project"
"login__add_new"   = "Create and enter"
"login__add_can"   = "Cancel"

"project__scripts" = "Scripts"